name: notariado
version: "1.0.0"
config-version: 2

profile: notariado

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  notariado:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table